name: GH PAGES

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    container: node:12.16.2

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: deploy doc
        shell: bash
        env:
          REPO_ORIGIN: ${{ secrets.REPO_ORIGIN }}
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${REPO_EMAIL}
          yarn gh-pages -d public -r ${REPO_ORIGIN}
